class AppStrings {
  static const Map<String, Map<String, String>> values = {
    'ar': {
      'app_name': 'نور الإيمان',
      'app_subtitle': 'رفيقك في دروب النور',
      'greeting': 'السلام عليكم',
      'hijri_date': 'التاريخ الهجري',
      'prayer_times': 'مواقيت الصلاة',
      'azkar': 'الأذكار',
      'names_of_allah': 'أسماء الله الحسنى',
      'tasbeeh': 'المسبحة',
      'favorites': 'المفضلة',
      'quick_actions': 'الوصول السريع',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'morning_azkar': 'أذكار الصباح',
      'evening_azkar': 'أذكار المساء',
      'sleep_azkar': 'أذكار النوم',
      'after_prayer_azkar': 'أذكار بعد الصلاة',
      'general_duas': 'أدعية عامة',
      'search': 'بحث...',
      'reset': 'إعادة ضبط',
      'next_prayer': 'الصلاة القادمة',
      'glow_text': 'نورك في كل وقت',
      'onboarding_1_title': 'أذكار وأدعية',
      'onboarding_1_desc': 'حصن نفسك بالأذكار والأدعية النبوية الصحيحة',
      'onboarding_2_title': 'مواقيت الصلاة',
      'onboarding_2_desc': 'تابع مواقيت الصلاة بدقة في أي مكان',
      'onboarding_3_title': 'أسماء الله الحسنى',
      'onboarding_3_desc': 'تعرف على معاني أسماء الله الحسنى بجمال وإتقان',
      'get_started': 'ابدأ الآن',
      'skip': 'تخطي',
      'hadiths': 'الأحاديث الشريفة',
      'qibla': 'اتجاه القبلة',
      'quran': 'القرآن الكريم',
      'location_disabled':
          'خدمات الموقع (GPS) معطلة. يرجى تفعيلها لتحديد القبلة',
      'location_denied': 'تم رفض صلاحية الموقع. يرجى السماح بها لتحديد القبلة',
      'enable_location': 'تفعيل الموقع',
      'retry': 'إعادة المحاولة',
      'stories': 'القصص',
      'stories_of_prophets': 'قصص الأنبياء والرسول',
      'knowledge_challenge': 'تحدي المعرفة',
      'score': 'النقاط',
      'adhan_settings': 'إعدادات الأذان',
      'enable_all_adhan': 'تفعيل الكُل',
      'custom_prayer_settings': 'تخصيص الصلوات',
      'test_adhan': 'تجربة الصوت',
      'stop_test': 'إيقاف الصوت',
      'next_question': 'المتابعة للتالي',
      'correct_answer_msg': 'إجابة صحيحة، أحسنت!',
      'wrong_answer_msg': 'إجابة خاطئة',
      'correct_answer_is': 'الجواب الصحيح هو:',
      'next': 'التالي',
      'charity': 'الصدقة والتبرع',
      'faith_journey': 'درب النور',
      'daily_streak': 'التزم لـ',
      'days': 'أيام',
      'mood_compass': 'بوصلة الروح',
      'feeling_anxious': 'أشعر بالقلق',
      'feeling_sad': 'أشعر بالحزن',
      'feeling_grateful': 'أشعر بالامتنان',
      'seeking_guidance': 'أبحث عن هداية',
      'soul_healing': 'شفاء القلوب',
      'location_error': 'خطأ في تحديد الموقع',
      'current_location': 'موقعك الحالي',
      'fajr_prayer': 'صلاة الفجر',
      'dhuhr_prayer': 'صلاة الظهر',
      'asr_prayer': 'صلاة العصر',
      'maghrib_prayer': 'صلاة المغرب',
      'isha_prayer': 'صلاة العشاء',
      'quran_reading': 'قراءة القرآن',
      'daily_azkar': 'الأذكار اليومية',
      'todays_achievements': 'إنجازات اليوم',
      'time_now': 'حان الوقت',
      'fajr': 'الفجر',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'tasbeeh_title': 'المسبحة',
      'quiz_title': 'اختبار',
      'prayer_times_title': 'أوقات الصلاة',
      'ayah_of_the_day': 'آية اليوم',
      'khatma': 'متتبع الختمة',
      'premium_settings': 'الإعدادات الفاخرة',
      'language_arabic': 'العربية',
      'language_english': 'إنجليزي',
      'quiz_progress': 'تقدم اللعبة',
      'notifications_title': 'التنبيهات',
      'about_app': 'عن التطبيق',
      'version_title': 'الإصدار',
      'reset_questions': 'إعادة تعيين الأسئلة',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'sticky_notification': 'إخطار ثابت للمواقيت',
      'facing_qibla': 'أنت تتجه نحو القبلة',
      'aim_at_qibla': 'وجه الجوال للقبلة',
      'no_questions': 'لا توجد أسئلة متاحة',
      'try_again': 'حاول مرة أخرى',
      'continue_reading': 'متابعة القراءة',
      'search_surah': 'ابحث عن سورة...',
      'verses_count': 'آية',
      'makkah': 'مكية',
      'madinah': 'مدنية',
      'no_stories_found': 'لا توجد قصص.',
      'how_is_your_heart': 'كيف تجد قلبك الآن؟',
      'suggested_dhikr': 'وردك المقترح',
      'reset_to_zero': 'إعادة ضبط',
      'clear_counter': 'تصفير العداد',
      'fix_status': 'إصلاح الإشعار',
      'notification_restarted': 'تمت إعادة تشغيل إشعار مواقيت الصلاة',
      'no_favorites_yet': 'لا توجد أذكار مفضلة بعد',
      'ob_location_title': 'تفعيل الموقع',
      'ob_location_desc':
          'نحتاج للوصول إلى موقعك لتحديد أوقات الصلاة واتجاه القبلة بدقة.',
      'no_items_found': 'لم يتم العثور على نتائج',
      'greeting_morning': 'صباح الخير',
      'greeting_afternoon': 'طاب مساؤك',
      'greeting_evening': 'مساء الخير',
      'remaining': 'متبقي',
      'hour': 'ساعة',
      'minute': 'دقيقة',
      'and': 'و',
      'reset_seen_questions': 'تصفير الأسئلة المكررة',
      'reset_start_fresh': 'إعادة الأسئلة من جديد',
      'reset_confirm_msg':
          'هل تريد حقاً مسح جميع الأسئلة التي شاهدتها والبدء من جديد؟',
      'reset_success_msg': 'تمت إعادة تعيين الأسئلة بنجاح',
      'dock_home': 'الرئيسية',
      'dock_quran': 'القرآن',
      'dock_tasbih': 'المسبحة',
      'dock_quiz': 'اختبار',
      'dock_prayer': 'الأوقات',
      'dock_settings': 'الإعدادات',
      'theme_dark_mode': 'الوضع الليلي',
      'theme_system': 'النظام',
      'live_stream': 'البث المباشر',
      'live_makkah': 'بث مكة المكرمة',
      'live_madinah': 'بث المدينة المنورة',
      'missed_prayers': 'قضاء الصلوات',
      'inspiration_of_the_day': 'رسالة اليوم',
      'location_needed_msg': 'يرجى تحديد الموقع لحساب أوقات الصلاة',
      'calculating_prayer_times': 'جاري حساب أوقات الصلاة...',
      'premium_version': 'بريميوم',
      'last_stop_position': 'مكان التوقف الأخير',
      'saved_at_verse': 'تم حفظ العلامة عند الآية',
      'bookmark_saved': 'تم حفظ العلامة',
      'sticky_notification_desc': 'عرض الوقت المتبقي في الإشعارات',
      'premium_ui': 'واجهة فاخرة',
      'today': 'اليوم',
      'makkah_name': 'مكة المكرمة, السعودية',
      'makkah_default': 'مكة المكرمة (افتراضي)',
      'edit_name': 'تعديل الاسم',
      'enter_name': 'أدخل اسمك',
      'save_name': 'حفظ',
      'user_name': 'الاسم',
      'calc_method': 'طريقة الحساب',
      'madhab': 'المذهب',
      'madhab_shafi': 'شافعي، مالكي، حنبلي',
      'madhab_hanafi': 'حنفي',
      'calc_method_auto': 'تلقائي (حسب الموقع)',
      'refresh_location': 'تحديث الموقع',
      'precision_location_desc': 'استخدام نظام GPS عالي الدقة للمواقيت',
      'calculation_settings': 'إعدادات الحساب الفلكي',
    },
    'en': {
      'app_name': 'NoorFaith',
      'app_subtitle': 'Your Journey of Light',
      'greeting': 'Assalamu Alaikum',
      'hijri_date': 'Hijri Date',
      'prayer_times': 'Prayer Times',
      'azkar': 'Azkar',
      'names_of_allah': '99 Names',
      'tasbeeh': 'Tasbeeh',
      'favorites': 'Favorites',
      'quick_actions': 'Quick Actions',
      'settings': 'Settings',
      'language': 'Language',
      'morning_azkar': 'Morning Azkar',
      'evening_azkar': 'Evening Azkar',
      'sleep_azkar': 'Sleep Azkar',
      'after_prayer_azkar': 'After Prayer Azkar',
      'general_duas': 'General Duas',
      'search': 'Search...',
      'reset': 'Reset',
      'next_prayer': 'Next Prayer',
      'glow_text': 'Your Light in Every Moment',
      'onboarding_1_title': 'Azkar & Duas',
      'onboarding_1_desc':
          'Protect yourself with authentic Azkar and prophetic Duas',
      'onboarding_2_title': 'Prayer Times',
      'onboarding_2_desc': 'Track prayer times accurately anywhere',
      'onboarding_3_title': '99 Names of Allah',
      'onboarding_3_desc':
          'Learn the meanings of the 99 Names of Allah beautifully',
      'get_started': 'Get Started',
      'skip': 'Skip',
      'hadiths': 'Hadiths',
      'qibla': 'Qibla Direction',
      'quran': 'Holy Quran',
      'location_disabled': 'Location services are disabled. Please enable them',
      'location_denied': 'Location permission denied. Please allow it',
      'enable_location': 'Enable Location',
      'open_settings': 'Open Settings',
      'retry': 'Retry',
      'stories': 'Stories',
      'stories_of_prophets': 'Stories of the Prophets',
      'knowledge_challenge': 'Knowledge Challenge',
      'score': 'Score',
      'adhan_settings': 'Adhan Settings',
      'enable_all_adhan': 'Enable All',
      'custom_prayer_settings': 'Custom Prayer Settings',
      'test_adhan': 'Test Audio',
      'stop_test': 'Stop Audio',
      'next_question': 'Continue',
      'correct_answer_msg': 'Correct Answer, Well Done!',
      'wrong_answer_msg': 'Wrong Answer',
      'correct_answer_is': 'The correct answer is:',
      'next': 'Next',
      'faith_journey': 'Faith Journey',
      'daily_streak': 'Streak for',
      'days': 'Days',
      'mood_compass': 'Soul Compass',
      'location_error': 'Location Error',
      'current_location': 'Current Location',
      'fajr_prayer': 'Fajr Prayer',
      'dhuhr_prayer': 'Dhuhr Prayer',
      'asr_prayer': 'Asr Prayer',
      'maghrib_prayer': 'Maghrib Prayer',
      'isha_prayer': 'Isha Prayer',
      'quran_reading': 'Quran Reading',
      'daily_azkar': 'Daily Azkar',
      'todays_achievements': "Today's Achievements",
      'time_now': 'Time now',
      'fajr': 'Fajr',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'tasbeeh_title': 'Tasbeeh',
      'quiz_title': 'Quiz',
      'prayer_times_title': 'Prayer Times',
      'ayah_of_the_day': 'Ayah of the Day',
      'khatma': 'Khatma Tracker',
      'premium_settings': 'Premium Settings',
      'language_arabic': 'Arabic',
      'language_english': 'English',
      'quiz_progress': 'Quiz Progress',
      'notifications_title': 'Notifications',
      'about_app': 'About',
      'version_title': 'Version',
      'reset_questions': 'Reset Questions',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'sticky_notification': 'Sticky Notification',
      'facing_qibla': 'Facing Qibla',
      'aim_at_qibla': 'Aim at Qibla',
      'no_questions': 'No questions available',
      'try_again': 'Try Again',
      'continue_reading': 'Continue Reading',
      'search_surah': 'Search surah...',
      'verses_count': 'Verses',
      'makkah': 'Makkah',
      'madinah': 'Madinah',
      'no_stories_found': 'No stories found.',
      'how_is_your_heart': 'How is your heart today?',
      'suggested_dhikr': 'Suggested Dhikr',
      'reset_to_zero': 'Reset to 0',
      'clear_counter': 'Clear counter',
      'fix_status': 'Fix Status',
      'notification_restarted': 'Prayer times notification restarted',
      'no_favorites_yet': 'No favorites yet',
      'ob_location_title': 'Enable Location',
      'ob_location_desc':
          'We need access to your location for accurate prayer times and Qibla.',
      'no_items_found': 'No items found',
      'greeting_morning': 'Good Morning',
      'greeting_afternoon': 'Good Afternoon',
      'greeting_evening': 'Good Evening',
      'remaining': 'Remaining',
      'hour': 'hour',
      'minute': 'minute',
      'and': 'and',
      'reset_seen_questions': 'Reset Seen Questions',
      'reset_start_fresh': 'Start questions pool from scratch',
      'reset_confirm_msg':
          'Do you really want to clear all seen questions and start fresh?',
      'reset_success_msg': 'Questions reset successfully',
      'dock_home': 'Home',
      'dock_quran': 'Quran',
      'dock_tasbih': 'Tasbih',
      'dock_quiz': 'Quiz',
      'dock_prayer': 'Prayer',
      'dock_settings': 'Settings',
      'theme_dark_mode': 'Dark Mode',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_change_subtitle': 'Change App Appearance',
      'story_not_found': 'Story not found',
      'inspiration_of_the_day': 'Inspiration of the Day',
      'location_needed_msg': 'Please enable location to calculate prayer times',
      'calculating_prayer_times': 'Calculating prayer times...',
      'premium_version': 'Premium',
      'last_stop_position': 'Last stop position',
      'saved_at_verse': 'Bookmark saved at verse',
      'bookmark_saved': 'Bookmark saved',
      'sticky_notification_desc': 'Show remaining time in notifications',
      'premium_ui': 'Premium UI',
      'today': 'Today',
      'makkah_name': 'Makkah, Saudi Arabia',
      'makkah_default': 'Makkah (Default)',
      'edit_name': 'Edit Name',
      'enter_name': 'Enter your name',
      'save_name': 'Save',
      'user_name': 'Name',
      'calc_method': 'Calculation Method',
      'madhab': 'Madhab / Asr Time',
      'madhab_shafi': 'Shafi, Maliki, Hanbali',
      'madhab_hanafi': 'Hanafi',
      'calc_method_auto': 'Automatic (Based on Location)',
      'refresh_location': 'Refresh Location',
      'precision_location_desc': 'Use high-precision GPS for times',
      'calculation_settings': 'Calculation Settings',
    },
  };

  static String get(String key, String lang) {
    // Default to 'ar' if language is unknown
    final activeLang = values.containsKey(lang) ? lang : 'ar';
    return values[activeLang]?[key] ?? values['en']?[key] ?? key;
  }
}
